# Generated by Django 2.2.6 on 2019-11-10 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cumRec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecord',
            name='examinerName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examinerrec', to='cumRec.Examiner'),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='gradeName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graderec', to='cumRec.ExaminerGrade'),
        ),
    ]
