# Generated by Django 2.2.6 on 2019-11-10 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cumRec', '0002_auto_20191110_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecord',
            name='examinerName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examinerrec', to='cumRec.Examiner'),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='gradeName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graderec', to='cumRec.ExaminerGrade'),
        ),
    ]
