# Generated by Django 2.2.6 on 2019-11-12 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cumRec', '0003_auto_20191110_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjectcourse', to='cumRec.Course'),
        ),
    ]
